# Generated by Django 3.0.2 on 2020-01-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeatmapSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osu_beatmapset_id', models.TextField(max_length=20)),
                ('artist', models.TextField()),
                ('title', models.TextField()),
                ('creator', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osu_user_id', models.TextField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beatmapset_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.BeatmapSet')),
            ],
        ),
    ]
