# Generated by Django 3.0.2 on 2020-01-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200125_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmapset',
            name='osu_beatmapset_id',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Beatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osu_beatmap_id', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=1)),
                ('version', models.TextField()),
                ('beatmapset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.BeatmapSet')),
            ],
        ),
    ]
